language: python
python:
  - "3.7"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda env create -q --file $TRAVIS_BUILD_DIR/environment_dev.yml -p $HOME/miniconda/envs/dem-tools

before_script:
  - conda activate dem-tools
  - cd $TRAVIS_BUILD_DIR/
  - pip install -e .

script: pytest